FROM node:latest

RUN mkdir -p /app
RUN apt update -y

#RUN npm install -g @vue/cli @vue/cli-service @vue/cli-plugin-babel @vue/cli-plugin-eslint @vue/babel-preset-app babel-eslint eslint eslint-plugin-vue vue-template-compiler
#ENTRYPOINT ["node"]
